"""Generate a JS SDK file that wraps the HTTP API so agents can run
multi-step operations in a single tool call via execute_js().

Anthropic's code-execution-with-MCP research (Nov 2025) showed that
agents writing code against a typed SDK — instead of chaining raw
tool calls — cut token usage by up to 98.7% on complex workflows
(e.g. 150k → 2k tokens). The reason: intermediate tool results no
longer have to flow through the model context twice, once in and
once back out with downstream transformations.

This generator emits a minimal ESM module with one exported function
per endpoint we care about. Claude writes small JS programs that
call several of these, filter + transform in-script, and return only
the final summary.

Security stance: the script runs under the user's own Node.js,
unsandboxed. Same trust boundary as the MCP server itself — the MCP
server is already allowed to read/write the vault and shell out to
git. Sandboxing is a future-us problem (quickjs, deno, firecracker).
"""

from __future__ import annotations

from pathlib import Path


SDK_MJS = r"""// Auto-generated by neurovault_server/js_sdk.py
// DO NOT EDIT BY HAND — regenerated on every server boot.
//
// Usage inside an execute_js() call:
//   import * as nv from './neurovault.mjs'
//   const hits = await nv.recall('token efficiency', { limit: 5 })
//   const ids = hits.map(h => h.engram_id)
//   const bodies = await Promise.all(ids.map(id => nv.getNote(id)))
//   console.log(JSON.stringify(bodies.map(b => b.title)))
//
// Anything written to stdout is returned to the agent as the tool
// result. If it parses as JSON the tool auto-parses it.

const API = process.env.NV_API_URL || "http://127.0.0.1:8765";

async function _get(path, params = null) {
  let url = `${API}${path}`;
  if (params) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(params)) {
      if (v !== undefined && v !== null) qs.append(k, String(v));
    }
    const s = qs.toString();
    if (s) url += `?${s}`;
  }
  const r = await fetch(url);
  if (!r.ok) throw new Error(`GET ${path} → ${r.status}`);
  return r.json();
}

async function _post(path, body = null) {
  const init = { method: "POST", headers: { "Content-Type": "application/json" } };
  if (body !== null) init.body = JSON.stringify(body);
  const r = await fetch(`${API}${path}`, init);
  if (!r.ok) throw new Error(`POST ${path} → ${r.status}`);
  return r.json();
}

async function _patch(path, body) {
  const r = await fetch(`${API}${path}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!r.ok) throw new Error(`PATCH ${path} → ${r.status}`);
  return r.json();
}

async function _delete(path) {
  const r = await fetch(`${API}${path}`, { method: "DELETE" });
  if (!r.ok) throw new Error(`DELETE ${path} → ${r.status}`);
  return r.json();
}

// --- Session + brain ------------------------------------------------------

export const sessionStart = ({ agentId, since } = {}) =>
  _get("/api/session_start", { agent_id: agentId, since });

export const listBrains = () => _get("/api/brains");
export const activeBrain = () => _get("/api/brains/active");
export const switchBrain = (brainId) => _post(`/api/brains/${brainId}/activate`);
export const createBrain = (name, description = "", vaultPath) =>
  _post("/api/brains", { name, description, vault_path: vaultPath });
export const brainStats = (brainId) => _get(`/api/brains/${brainId}/stats`);

// --- Memory write ---------------------------------------------------------

export const remember = ({ content, title = "", agent_id, folder } = {}) =>
  _post("/api/notes", { content, title, agent_id, folder });

export const rememberBatch = async (items) =>
  Promise.all(items.map(i => remember(i)));

export const checkDuplicate = (content, threshold = 0.85, limit = 5) =>
  _post("/api/check_duplicate", { content, threshold, limit });

export const renameNote = (engramId, { filename, title } = {}) =>
  _patch(`/api/notes/${engramId}`, { filename, title });

export const forget = (engramId) => _delete(`/api/notes/${engramId}`);

// --- Memory read ----------------------------------------------------------

export const recall = (q, { limit = 10, mode = "preview", as_of, rerank = false } = {}) =>
  _get("/api/recall", { q, limit, mode, as_of, rerank });

export const recallChunks = (q, { top_k = 10, granularity = "paragraph" } = {}) =>
  _get("/api/recall/chunks", { q, top_k, granularity });

export const getNote = (engramId) => _get(`/api/notes/${engramId}`);
export const listNotes = () => _get("/api/notes");
export const changesSince = (sinceIso, limit = 100) =>
  _get("/api/changes", { since: sinceIso, limit });

// --- Multi-agent todos ----------------------------------------------------

export const addTodo = (task, { context = "", to_agent = "any", from_agent } = {}) =>
  _post("/api/todos", { task, context, to_agent, from_agent });

export const claimTodo = (agentId) =>
  _post(`/api/todos/next/claim`, { agent_id: agentId });

export const completeTodo = (todoId, result = "") =>
  _post(`/api/todos/${todoId}/complete`, { result });

export const listTodos = ({ status, agent_id, limit = 50 } = {}) =>
  _get("/api/todos", { status, agent_id, limit });

// --- Compilation ----------------------------------------------------------

export const prepareCompile = (topic) =>
  _post("/api/compilations/prepare", { topic });

export const submitCompile = (topic, wiki_markdown, source_engram_ids) =>
  _post("/api/compilations/submit", { topic, wiki_markdown, source_engram_ids });

// --- Helpers --------------------------------------------------------------

// Print a value so it's captured as the execute_js result. Objects are
// JSON-stringified; strings and numbers are printed as-is.
export function out(value) {
  if (typeof value === "string") console.log(value);
  else console.log(JSON.stringify(value));
}
"""


def sdk_path(nv_home: Path) -> Path:
    """Canonical on-disk location for the emitted SDK."""
    return nv_home / "sdk" / "neurovault.mjs"


def write_sdk(nv_home: Path) -> Path:
    """Write (or overwrite) the SDK at `<nv_home>/sdk/neurovault.mjs`.

    Idempotent — safe to call on every server boot. The content is a
    fixed string today; when/if we add introspection-driven generation
    (scan @mcp.tool registrations and build the SDK from them), this
    function becomes the one place to update.
    """
    path = sdk_path(nv_home)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(SDK_MJS, encoding="utf-8")
    return path


__all__ = ["write_sdk", "sdk_path", "SDK_MJS"]
