#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES.md from the three manifests.
#
# Best-effort: each block tries to run its license tool and falls back
# to a stub if the tool isn't installed. The resulting file is diffed
# against the committed one in CI so a stale notice file fails the
# release build (forcing a refresh commit before the tag lands).
#
# Usage:
#   bash scripts/gen_third_party_notices.sh           # regenerate in place
#   bash scripts/gen_third_party_notices.sh --check   # fail if regen would change the file
#
# Tooling:
#   - Python: pip-licenses (install with: uv pip install pip-licenses)
#   - JS:     npx license-checker (auto-installed)
#   - Rust:   cargo-about (install with: cargo install cargo-about)

set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD_PARTY_NOTICES.md"
TMP="$(mktemp)"

header() {
  cat <<'EOF'
# Third-Party Notices

NeuroVault is MIT-licensed (see [LICENSE](LICENSE)). The shipped application
bundles third-party software whose licenses are preserved below. This file
is regenerated by `scripts/gen_third_party_notices.sh` — do not edit by hand.

Only **runtime** dependencies are listed. Dev / test tooling (pytest,
PyInstaller, Vite, TypeScript, Tailwind) ships with its own license text
inside its own package and isn't redistributed by us.

---

EOF
}

python_block() {
  echo "## Python MCP server (runtime)"
  echo ""
  if command -v pip-licenses >/dev/null 2>&1; then
    (cd server && pip-licenses --format=markdown --with-urls --no-license-path 2>/dev/null) \
      || echo "*Could not run pip-licenses in server/ — declared deps in [pyproject.toml](server/pyproject.toml).*"
  else
    echo "*pip-licenses not installed — declared deps in [pyproject.toml](server/pyproject.toml). Install: \`uv pip install pip-licenses\`.*"
  fi
  echo ""
}

js_block() {
  echo "## Frontend (React / Tauri UI)"
  echo ""
  if command -v npx >/dev/null 2>&1; then
    # --production excludes devDeps; --markdown emits GFM table.
    npx --yes license-checker --production --markdown 2>/dev/null \
      || echo "*license-checker failed — declared deps in [package.json](package.json).*"
  else
    echo "*npx not available — declared deps in [package.json](package.json).*"
  fi
  echo ""
}

rust_block() {
  echo "## Rust (Tauri desktop)"
  echo ""
  if command -v cargo-about >/dev/null 2>&1; then
    (cd src-tauri && cargo about generate about.hbs 2>/dev/null) \
      || echo "*cargo-about config missing — declared crates in [Cargo.toml](src-tauri/Cargo.toml).*"
  else
    echo "*cargo-about not installed — declared crates in [Cargo.toml](src-tauri/Cargo.toml). Install: \`cargo install cargo-about\`.*"
  fi
  echo ""
}

{
  header
  python_block
  js_block
  rust_block
  echo "---"
  echo ""
  echo "*Last regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*"
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$OUT" "$TMP" >/dev/null 2>&1; then
    echo "THIRD_PARTY_NOTICES.md is out of date. Run:"
    echo "  bash scripts/gen_third_party_notices.sh"
    diff -u "$OUT" "$TMP" || true
    rm -f "$TMP"
    exit 1
  fi
  rm -f "$TMP"
  echo "THIRD_PARTY_NOTICES.md is current."
else
  mv "$TMP" "$OUT"
  echo "Wrote $OUT"
fi
